2021-02-02 20:43:28,737 ERROR: Exception on / [GET] [in /home/tund/anaconda3/envs/flmyblog/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/tund/anaconda3/envs/flmyblog/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/tund/anaconda3/envs/flmyblog/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/tund/anaconda3/envs/flmyblog/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/tund/anaconda3/envs/flmyblog/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/tund/anaconda3/envs/flmyblog/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/tund/anaconda3/envs/flmyblog/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/tund/anaconda3/envs/flmyblog/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/media/tund/HDD/myblog/app/routes.py", line 29, in index
    page, app.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'
